[project]
name = "find-my-kitten"
version = "0.1.0"
requires-python = "==3.12.3"
dependencies = [
    "numpy>=2.0.0",
    "opencv-python",
    "torch>=1.1.0",
    "torchvision",
    "pandas",
    "yt-dlp",
    "supervision",
    "empy==3.3.4",
    "pyros-genmsg",
    "setuptools",
    "kconfiglib",
    "jsonschema",
    "jinja2",
    "pyserial",
    "pyyaml",
    "packaging",
    "toml",
    "catkin_pkg",
    "lark"
    "ultralytics",
    "seaborn",
<<<<<<< HEAD
<<<<<<< HEAD
]
=======
]
>>>>>>> e4c4a02 (feat: Add script to run Isaac Sim and required scripts)
=======
    "catkin_pkg",
    "lark"
]
>>>>>>> 4bb0a63 (Added the lock file)
