isaac:
  script: "isaac_simple_obstacles.py"
  args: ['']  # Optional

px4:
  script: "ball_finder.py"
  delay_seconds: 30.0

cameras:
  down_facing:
    topic: "/drone1/down_facing_camera/color/image_raw"
  zed_left:
    topic: "/drone1/zed_left_camera/color/image_raw"
  zed_right:
    topic: "/drone1/zed_right_camera/color/image_raw"

object_detector:
  enabled: true
  input_topic_name: "/drone1/down_facing_camera/color/image_raw"
  pytorch_model_path: "yolov5s.pt"
